[package]
name = "real_ua_cli"
version = "0.1.0"
edition = "2021"
readme = "../README.md"
license-file = "../LICENSE"
description = "generates random http user-agent to stdout"

[dependencies]
real_ua = { path = "../real_ua", version = "0.1.0" }